	/*
	 * ConstraintParameter.cu
	 * 
	 * ***************   Notice   ***************
	 * Auto Generated By ATPC on:2017-12-01 17:32:46
	 * Author: ZhangHui
	 * 
	 */ 

	#include <iostream>

	#include "./../solver/type.h"
	#include "./../solver/ConstantValue.h"
	#include "./../model/RuntimeValue.h"
	#include "ConstraintParameter.cuh"

	using namespace std;


	/*
	 * 约束的名字信息
	 * */ 
	string ConstraintParameter::constraintName = "benchmark67";

	/*
	 * 约束的变量类型，使用bool变量表示，1表示浮点数，0表示整形
	 * */ 
	bool ConstraintParameter::constraintVarType[NUM_OF_PARAM] = { 1 , 1 , 1 , 1 , 1 , 1 };

	/*
	 * 变量的名字信息
	 * */ 
	string ConstraintParameter::constraintVarName[NUM_OF_PARAM] = { "x" , "y" , "z" , "w" , "t" , "v" };

	/*
	 * 变量的整体依赖关系，使用bool变量表示，1表示相关，0表示不相关
	 * */ 
	bool ConstraintParameter::constraintDependencyRela[NUM_OF_PARAM] = { true , true , true , true , true , true };

	/*
	 * 所有的约束的比较运算符的类型信息
	 * 1 表示> , >= , < , <=四种情况
	 * 0 表示 == 情况
	 * -1 表示 ！= 情况
	 * */ 
	int ConstraintParameter::constraintCompType[Num_Of_Constraints] =  { 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 };

	/*
	 * 这个函数是用来获取约束的信息
	 * */ 
	vector< vector<string> > ConstraintParameter::getConstraintInfo()
	{
		vector< vector<string> > res;

		vector<string> HeQv1;
		HeQv1.push_back("x-y+tan(v)>(z+t)/(w+t)");
		HeQv1.push_back("sqrt(x-t)>z/y");
		HeQv1.push_back("log(x*y)>log(t+w+z)");
		HeQv1.push_back("pow(y,t)*cos(v)>z*2+w*3+x*7");
		HeQv1.push_back("z+w>x+y");
		HeQv1.push_back("x/y>w");
		HeQv1.push_back("x>(w+y-z)");
		HeQv1.push_back("sqrt(w*y*z)>log10(t*x)");
		HeQv1.push_back("x*cos(t+y)>log(w*z*3)");
		HeQv1.push_back("cos(t)*sin(v)>cos(y)");

		res.push_back(HeQv1);

		return res;
	}

	/*
	 * 这个函数是用来获取约束的运行时刻值，用于CPU验证
	 * */ 
	vector< vector<RuntimeValue*> > ConstraintParameter::getCoveredInfo(FloatType* nums)
	{
		vector< vector<RuntimeValue*> > res;

		vector<RuntimeValue*> HeQv1;

		RuntimeValue* tmp_0_0 = getConstraintValue_0_0(nums[0] , nums[1] , nums[2] , nums[3] , nums[4] , nums[5]);
		HeQv1.push_back(tmp_0_0);
		RuntimeValue* tmp_0_1 = getConstraintValue_0_1(nums[0] , nums[1] , nums[2] , nums[3] , nums[4] , nums[5]);
		HeQv1.push_back(tmp_0_1);
		RuntimeValue* tmp_0_2 = getConstraintValue_0_2(nums[0] , nums[1] , nums[2] , nums[3] , nums[4] , nums[5]);
		HeQv1.push_back(tmp_0_2);
		RuntimeValue* tmp_0_3 = getConstraintValue_0_3(nums[0] , nums[1] , nums[2] , nums[3] , nums[4] , nums[5]);
		HeQv1.push_back(tmp_0_3);
		RuntimeValue* tmp_0_4 = getConstraintValue_0_4(nums[0] , nums[1] , nums[2] , nums[3] , nums[4] , nums[5]);
		HeQv1.push_back(tmp_0_4);
		RuntimeValue* tmp_0_5 = getConstraintValue_0_5(nums[0] , nums[1] , nums[2] , nums[3] , nums[4] , nums[5]);
		HeQv1.push_back(tmp_0_5);
		RuntimeValue* tmp_0_6 = getConstraintValue_0_6(nums[0] , nums[1] , nums[2] , nums[3] , nums[4] , nums[5]);
		HeQv1.push_back(tmp_0_6);
		RuntimeValue* tmp_0_7 = getConstraintValue_0_7(nums[0] , nums[1] , nums[2] , nums[3] , nums[4] , nums[5]);
		HeQv1.push_back(tmp_0_7);
		RuntimeValue* tmp_0_8 = getConstraintValue_0_8(nums[0] , nums[1] , nums[2] , nums[3] , nums[4] , nums[5]);
		HeQv1.push_back(tmp_0_8);
		RuntimeValue* tmp_0_9 = getConstraintValue_0_9(nums[0] , nums[1] , nums[2] , nums[3] , nums[4] , nums[5]);
		HeQv1.push_back(tmp_0_9);

		res.push_back(HeQv1);

		return res;
	}

	/*
	 * 下面是最后在CPU对求出的可行解向量做验证的函数，
	 * 主要就是计算每一个简单子约束的运行时刻值，以及每一个简单自约束的满足情况
	 * */ 
	RuntimeValue* ConstraintParameter::getConstraintValue_0_0( FloatType x , FloatType y , FloatType z , FloatType w , FloatType t , FloatType v )
	{
		FloatType value = ( x-y+tan(v) ) - ( (z+t)/(w+t) );
		bool isCovered = (x-y+tan(v)>(z+t)/(w+t)) * true;
		RuntimeValue* one = new RuntimeValue(value,isCovered);
		return one;
	}

	RuntimeValue* ConstraintParameter::getConstraintValue_0_1( FloatType x , FloatType y , FloatType z , FloatType w , FloatType t , FloatType v )
	{
		FloatType value = ( sqrt(x-t) ) - ( z/y );
		bool isCovered = (sqrt(x-t)>z/y) * true;
		RuntimeValue* one = new RuntimeValue(value,isCovered);
		return one;
	}

	RuntimeValue* ConstraintParameter::getConstraintValue_0_2( FloatType x , FloatType y , FloatType z , FloatType w , FloatType t , FloatType v )
	{
		FloatType value = ( log(x*y) ) - ( log(t+w+z) );
		bool isCovered = (log(x*y)>log(t+w+z)) * true;
		RuntimeValue* one = new RuntimeValue(value,isCovered);
		return one;
	}

	RuntimeValue* ConstraintParameter::getConstraintValue_0_3( FloatType x , FloatType y , FloatType z , FloatType w , FloatType t , FloatType v )
	{
		FloatType value = ( pow(y,t)*cos(v) ) - ( z*2+w*3+x*7 );
		bool isCovered = (pow(y,t)*cos(v)>z*2+w*3+x*7) * true;
		RuntimeValue* one = new RuntimeValue(value,isCovered);
		return one;
	}

	RuntimeValue* ConstraintParameter::getConstraintValue_0_4( FloatType x , FloatType y , FloatType z , FloatType w , FloatType t , FloatType v )
	{
		FloatType value = ( z+w ) - ( x+y );
		bool isCovered = (z+w>x+y) * true;
		RuntimeValue* one = new RuntimeValue(value,isCovered);
		return one;
	}

	RuntimeValue* ConstraintParameter::getConstraintValue_0_5( FloatType x , FloatType y , FloatType z , FloatType w , FloatType t , FloatType v )
	{
		FloatType value = ( x/y ) - ( w );
		bool isCovered = (x/y>w) * true;
		RuntimeValue* one = new RuntimeValue(value,isCovered);
		return one;
	}

	RuntimeValue* ConstraintParameter::getConstraintValue_0_6( FloatType x , FloatType y , FloatType z , FloatType w , FloatType t , FloatType v )
	{
		FloatType value = ( x ) - ( (w+y-z) );
		bool isCovered = (x>(w+y-z)) * true;
		RuntimeValue* one = new RuntimeValue(value,isCovered);
		return one;
	}

	RuntimeValue* ConstraintParameter::getConstraintValue_0_7( FloatType x , FloatType y , FloatType z , FloatType w , FloatType t , FloatType v )
	{
		FloatType value = ( sqrt(w*y*z) ) - ( log10(t*x) );
		bool isCovered = (sqrt(w*y*z)>log10(t*x)) * true;
		RuntimeValue* one = new RuntimeValue(value,isCovered);
		return one;
	}

	RuntimeValue* ConstraintParameter::getConstraintValue_0_8( FloatType x , FloatType y , FloatType z , FloatType w , FloatType t , FloatType v )
	{
		FloatType value = ( x*cos(t+y) ) - ( log(w*z*3) );
		bool isCovered = (x*cos(t+y)>log(w*z*3)) * true;
		RuntimeValue* one = new RuntimeValue(value,isCovered);
		return one;
	}

	RuntimeValue* ConstraintParameter::getConstraintValue_0_9( FloatType x , FloatType y , FloatType z , FloatType w , FloatType t , FloatType v )
	{
		FloatType value = ( cos(t)*sin(v) ) - ( cos(y) );
		bool isCovered = (cos(t)*sin(v)>cos(y)) * true;
		RuntimeValue* one = new RuntimeValue(value,isCovered);
		return one;
	}

